version: 0.2

env:
  variables:
    JAVA_HOME: "/opt/java17"
    PATH: "${JAVA_HOME}/bin:${PATH}"

phases:
  install:
    runtime-versions:
      java: corretto-17
  build:
    commands:
      - mvn clean install
  post_build:
    commands:
      - echo Build completed
artifacts:
  files:
    - target/*.jar
    - scripts/*.sh
    - appspec.yml
  discard-paths: yes
